language: python
python:
- '3.6'
- '3.7'
cache: pip
before_install:
- wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O
  miniconda.sh
- export MINICONDA_PREFIX="$HOME/miniconda"
- bash miniconda.sh -b -p $MINICONDA_PREFIX
- export PATH="$MINICONDA_PREFIX/bin:$PATH"
- conda config --set always_yes yes
- conda update -q conda
- conda config --add channels bioconda
- conda config --add channels conda-forge
- conda info -a
install:
- conda create -n test-env pytest pytest-cov python-coveralls python=$TRAVIS_PYTHON_VERSION pandas scikit-bio prodigal
  mmseqs2!=10.6d92c hmmer trnascan-se >=2 sqlalchemy barrnap altair >=4 openpyxl networkx ruby parallel
- source activate test-env
- conda list
- pip install --no-cache-dir --editable .
script:
- py.test --cov DRAM --cov-report term-missing
after_success:
- coveralls
